# Generated by Django 2.2.6 on 2021-02-15 08:31

from django.db import migrations, models
import django.utils.timezone
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=project.models.user_directory_path_photo),
            preserve_default=False,
        ),
    ]
