# Generated by Django 2.2.6 on 2021-02-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20210218_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='marital_status',
            field=models.IntegerField(choices=[(1.1, 'Не женат'), (1.2, 'Женат'), (2.1, 'Не замужем'), (2.2, 'Замужем'), (1.3, 'Влюблен'), (2.3, 'Влюблена'), (3, 'В активном поиске')], default=1),
            preserve_default=False,
        ),
    ]
