# Generated by Django 2.2.6 on 2021-02-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_person_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='marital_status',
            field=models.FloatField(choices=[(1.1, 'Не женат'), (1.2, 'Женат'), (2.1, 'Не замужем'), (2.2, 'Замужем'), (1.3, 'Влюблен'), (2.3, 'Влюблена'), (3, 'В активном поиске')]),
        ),
    ]
