# Generated by Django 2.2.6 on 2021-02-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20210224_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='marital_status',
            field=models.CharField(choices=[('Не женат', 'Не женат'), ('Женат', 'Женат'), ('Не замужем', 'Не замужем'), ('Замужем', 'Замужем'), ('Влюблен', 'Влюблен'), ('Влюблена', 'Влюблена'), ('В активном поиске', 'В активном поиске')], max_length=20),
        ),
    ]
