# Generated by Django 2.2.6 on 2021-03-02 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20210224_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='re_post',
            name='user',
        ),
    ]
