# Generated by Django 2.2.6 on 2021-03-03 09:18

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20210303_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(null=True, upload_to=project.models.user_directory_path_photo),
        ),
    ]
