# Generated by Django 2.2.6 on 2021-03-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20210303_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date_pub',
            field=models.DateField(auto_now=True),
        ),
    ]
