# Generated by Django 2.2.6 on 2021-03-03 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20210303_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='album',
        ),
    ]
