# Generated by Django 2.2.6 on 2021-03-03 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_auto_20210303_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='description',
            new_name='descriptionAlbum',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='description',
            new_name='descriptionPhoto',
        ),
    ]
