# Generated by Django 2.2.6 on 2021-03-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_auto_20210303_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='descriptionPhoto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
