# Generated by Django 2.2.6 on 2021-03-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_auto_20210304_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='descriptionAlbum',
            field=models.CharField(max_length=150),
        ),
    ]
