# Generated by Django 2.2.6 on 2021-03-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_auto_20210306_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='descriptionAlbum',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
