# Generated by Django 2.2.6 on 2021-03-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_auto_20210306_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='author_track',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='audio',
            name='title_track',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
