# Generated by Django 2.2.6 on 2021-03-16 16:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0029_auto_20210312_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='Подписчики', to=settings.AUTH_USER_MODEL),
        ),
    ]
