# Generated by Django 2.2.6 on 2021-03-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_group_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='quote',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
